In [ ]:
# The above data is data for prebid auctions. 
# There are bidders who receive requests for placing ads, they respond to these requests with a bid and the highest bid wins the auction. 
# Analyze the dataset to answer which bidder has the highest win rate (wins / total_bid).

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns',None)

In [3]:
bid_df = pd.read_csv(r"C:\Users\Shivani\Downloads\analysis_id(in).csv", index_col=False)

In [4]:
bid_df.shape

(5000, 27)

In [7]:
bid_df.columns

Index(['date_hour', 'client', 'device_type', 'time_zone', 'os_name',
       'browser_name', 'ad_unit', 'size', 'bidder', 'bid_range', 'media_type',
       'request_count', 'response_count', 'prebid_win_count', 'win_count',
       'sum_bid', 'sum_time_to_respond', 'median', 'min_bid', 'max_bid',
       'avg_bid', 'sum_2nd_highest_bid', 'sum_prebid_winning_bid',
       'sum_winning_bid', 'sum_nobid', 'sum_timeout'],
      dtype='object')

In [6]:
bid_df.drop(['Unnamed: 0'], axis=1, inplace=True)

In [12]:
bid_df.ad_unit.nunique()

260

In [ ]:
# bid_df.drop(['date_hour', 'client', 'device_type', 'time_zone', 'os_name','browser_name']) Columns to be dropped during data prep for model training

In [11]:
bid_df.columns

Index(['date_hour', 'client', 'device_type', 'time_zone', 'os_name',
       'browser_name', 'ad_unit', 'size', 'bidder', 'bid_range', 'media_type',
       'request_count', 'response_count', 'prebid_win_count', 'win_count',
       'sum_bid', 'sum_time_to_respond', 'median', 'min_bid', 'max_bid',
       'avg_bid', 'sum_2nd_highest_bid', 'sum_prebid_winning_bid',
       'sum_winning_bid', 'sum_nobid', 'sum_timeout'],
      dtype='object')

In [13]:
bid_df.win_count.value_counts()

win_count
1.0     150
2.0      20
3.0       5
4.0       5
6.0       2
13.0      1
5.0       1
16.0      1
7.0       1
Name: count, dtype: int64

In [24]:
bid_df.query("bidder=='onemobile'")

,date_hour,client,device_type,time_zone,os_name,browser_name,ad_unit,size,bidder,bid_range,media_type,request_count,response_count,prebid_win_count,win_count,sum_bid,sum_time_to_respond,median,min_bid,max_bid,avg_bid,sum_2nd_highest_bid,sum_prebid_winning_bid,sum_winning_bid,sum_nobid,sum_timeout
0,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-Footers,728x90,onemobile,0.5-0.6,display,4,4,1.0,NaN,2.340800,6614.0,NaN,0.585200,0.585200,0.585200,0.585200,0.585200,NaN,NaN,NaN
8,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-SideBar-1,300x250,onemobile,1-1.1,display,1,1,NaN,NaN,1.036109,2064.0,NaN,1.036109,1.036109,1.036109,NaN,NaN,NaN,NaN,NaN
9,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-SideBar-T,300x600,onemobile,0.7-0.8,display,1,1,1.0,NaN,0.709107,1896.0,NaN,0.709107,0.709107,0.709107,NaN,0.709107,NaN,NaN,NaN
28,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Macintosh,Chrome-89.043899,div-gpt-ad-BT-D-Sidebar-B,300x250,onemobile,0.2-0.3,display,1,1,NaN,NaN,0.234080,1099.0,NaN,0.234080,0.234080,0.234080,NaN,NaN,NaN,NaN,NaN
50,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Windows,Chrome-89.043899,div-gpt-ad-BT-D-SideBar-1,300x250,onemobile,2.5-2.6,display,1,1,1.0,NaN,2.566520,1090.0,NaN,2.566520,2.566520,2.566520,NaN,2.566520,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4954,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InLine-1,300x250,onemobile,0.9-1,display,6,6,4.0,NaN,5.543124,3009.0,NaN,0.902880,0.967306,0.923854,NaN,3.628240,NaN,NaN,NaN
4980,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-5_1_9,300x250,onemobile,2-2.1,display,1,1,1.0,NaN,2.062723,1527.0,2.062723,2.062723,2.062723,2.062723,NaN,2.062723,NaN,NaN,NaN
4985,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-6_2_6,300x250,onemobile,0.1-0.2,display,1,1,1.0,NaN,0.199083,206.0,0.199083,0.199083,0.199083,0.199083,NaN,0.199083,NaN,NaN,NaN
4987,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-7_1_11,300x250,onemobile,0.4-0.5,display,1,1,1.0,NaN,0.449521,427.0,NaN,0.449521,0.449521,0.449521,NaN,0.449521,NaN,NaN,NaN
4990,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-8_1_13,300x250,onemobile,0.1-0.2,display,1,1,NaN,NaN,0.162439,2220.0,0.162439,0.162439,0.162439,0.162439,0.162439,NaN,NaN,NaN,NaN

In [ ]:
bid_df.head()

,date_hour,client,device_type,time_zone,os_name,browser_name,ad_unit,size,bidder,bid_range,media_type,request_count,response_count,prebid_win_count,win_count,sum_bid,sum_time_to_respond,median,min_bid,max_bid,avg_bid,sum_2nd_highest_bid,sum_prebid_winning_bid,sum_winning_bid,sum_nobid,sum_timeout
0,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-Footers,728x90,onemobile,0.5-0.6,display,4,4,1.0,NaN,2.34080,6614.0,NaN,0.58520,0.58520,0.585200,0.5852,0.5852,NaN,NaN,NaN
1,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-Footers,728x90,rhythmone,0.3-0.4,display,3,3,NaN,NaN,1.03230,5171.0,NaN,0.33945,0.34875,0.344100,NaN,NaN,NaN,NaN,NaN
2,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-InLine-1,300x250,undertone,0.9-1,display,1,1,NaN,NaN,0.96000,1523.0,NaN,0.96000,0.96000,0.960000,NaN,NaN,NaN,NaN,NaN
3,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-O-300x250-1,300x250,,,display,43,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-O-300x250-1,300x250,rhythmone,0.3-0.4,display,2,2,NaN,NaN,0.69285,3570.0,0.34875,0.34410,0.34875,0.346425,NaN,NaN,NaN,NaN,NaN

In [ ]:
test_df_1 = bid_df.groupby('bidder').agg({'request_count':'sum','response_count':'sum','prebid_win_count':'sum','win_count':'sum','avg_bid':'sum'})

In [20]:
test_df_1['win_rate'] = (test_df_1['win_count']/test_df_1['response_count'])*100

In [23]:
test_df_1.sort_values(by='win_rate', ascending=False)

,request_count,response_count,prebid_win_count,win_count,win_rate
bidder,,,,,
undertone,104,104,52.0,16.0,15.384615
emx_digital,393,393,56.0,20.0,5.089059
sharethrough,332,332,104.0,10.0,3.012048
rhythmone,655,655,160.0,18.0,2.748092
pulsepoint,191,191,71.0,5.0,2.617801
pubmatic,2335,2335,255.0,57.0,2.441113
teads,700,700,323.0,16.0,2.285714
33across,886,886,136.0,19.0,2.144470
onemobile,2726,2726,759.0,35.0,1.283933
appnexus,830,830,175.0,10.0,1.204819
medianet,2556,2556,253.0,20.0,0.782473
triplelift,1479,1479,108.0,10.0,0.676133
criteo,3181,3181,587.0,21.0,0.660170
openx,1165,1165,86.0,7.0,0.600858
ix,3051,3051,184.0,13.0,0.426090
sovrn,358,358,14.0,1.0,0.279330
rubicon,582,582,33.0,0.0,0.000000
,261724,0,0.0,0.0,NaN

In [ ]:
# bid_df.groupby('bidder')[]

In [ ]:
# Describe how you would build a logistic regression model to predict the probability of a bid winning (win) based on the other columns. 
# What features would you select and why?

In [ ]:
# To build a logistic regression model,
# I will create a column that will be the target variable (win) for logistic regression, it will have value 1 for every bid win (win_count > 0) and 0 (win_count =< 0) for missed wins
# The Features I will include in the model are ('bidder','request_count', 'response_count', 'prebid_win_count', 'win_count','sum_bid','avg_bid') as my assumption is that these feature
# Will have a correlation with the target variable (win), In my approach I would train the model after basic preprocessing and missing values handling to get a baseline accuracy score from the model first.
# Additionally, I would scale the features if the baseline model fails to run on the varying scale of values, Idea is to build on top of the baseline model incrementally. I would also experiment with feature engineering
# Where I would create metrics such as request to response ratio which would tell if the bidder tends to skip certain requests, these features would be checked for correlation with the target variable and I would
# check the model coefficient to verify if the right features are getting the high coeff by the model, I would tweak the penalty term to L1 regularization(to simplify the model and keep relevant features)
# or I would tweak the penalty term to L2 regularization(to keep the selected features accountable for model performance) the decision would depend upon the model performance on the data

In [ ]:
# win rate = wins(win_count)/total_bid